# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasAssoc',
            fields=[
                ('attribDate', models.DateField(null=True)),
                ('aliasAssocKey', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AliasIden',
            fields=[
                ('lastName', models.CharField(max_length=256)),
                ('firstName', models.CharField(max_length=256)),
                ('otherName', models.CharField(max_length=512)),
                ('dateOfBirth', models.DateField(null=True)),
                ('cityOfBirth', models.CharField(max_length=256)),
                ('countryOfBirth', models.CharField(max_length=256)),
                ('dateTimeAdded', models.DateTimeField(auto_now_add=True)),
                ('aliasIdenKey', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('referenceOne', models.CharField(max_length=25)),
                ('referenceTwo', models.CharField(max_length=25)),
                ('caseNameOne', models.CharField(max_length=256)),
                ('caseNameTwo', models.CharField(max_length=256)),
                ('caseRefKey', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('docType', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MainIden',
            fields=[
                ('lastName', models.CharField(max_length=256)),
                ('firstName', models.CharField(max_length=256)),
                ('otherName', models.CharField(max_length=512)),
                ('dateOfBirth', models.DateField(null=True)),
                ('cityOfBirth', models.CharField(max_length=256)),
                ('countryOfBirth', models.CharField(max_length=256)),
                ('dateTimeAdded', models.DateTimeField(auto_now_add=True)),
                ('mainIdenKey', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='aliasassoc',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fms.AliasIden'),
        ),
        migrations.AddField(
            model_name='aliasassoc',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fms.MainIden'),
        ),
        migrations.AddField(
            model_name='aliasassoc',
            name='sourceDocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fms.Document'),
        ),
    ]
