# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('optionalPrefix', models.CharField(max_length=255)),
                ('streetNumber', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('addressLineOne', models.CharField(max_length=255)),
                ('addressLineTwo', models.CharField(max_length=255)),
                ('addressLineThree', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('dateTimeAdded', models.DateTimeField(auto_now_add=True)),
                ('addresKey', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='mainiden',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Non-Binary')], max_length=12, null=True),
        ),
    ]
