# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_auto_20170207_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task', models.CharField(max_length=2048)),
                ('priority', models.CharField(max_length=25)),
                ('dueDate', models.DateField()),
                ('taskKey', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mainiden',
            name='otherName',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
